CLASS LHC_ZZLIR_LIB_BOOK_MNT_1313 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzlirLibBookMnt1313
        RESULT result.
ENDCLASS.

CLASS LHC_ZZLIR_LIB_BOOK_MNT_1313 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
